### ISSUE TITLE
Exemplo PHP

### ISSUE THREAD

**Issue by lpex-code** [tamojuno/integration-api-php-sdk#10]
Boa tarde

A SDK PHP mesmo usando os metodos de autenticação e chamadas apenas gera erro, não conecta na API.

Conseguem dar um help?

**Comment by kevinhf35** [comment]
Opa blz Ipex? Cara também ralei pra conseguir fazer essa API funcionar, tem uma classe que um cara criou que é bem mais fácil, e foi por ela que fiz a integração... tem boleto e cartão de credito, essa é a classe: 

https://github.com/ylmenezes/php-juno-v2

Voce vai precisar criar conta no sandbox da juno > validar o email e os dados > gerar o token publico > gerar o token privado > criar uma credencial > pegar a senha > pegar o usuario.

Depois pega o diretorio que te passei no link e altera as informacões no arquivo config, ai é só entrar nos exemplos e testar. o nome do arquivo para gerar o boleto é createCharge se não me engano, para gerar boletos você precisa de umas 5 informações:

CPF ou CNPJ
Nome
Valor
Data de vencimento (precisa ser no proprio dia ou acima)
Numero de dias que pode receber após o vencimento

Basicamente é isso ;)

**Comment by lpex-code** [comment]
Valeu pela ajuda @kevinhf35. 

Gero o token desta forma:

$base64 = base64_encode("{$clientId}:{$clientSecret}");

$token         = 'Basic {$base64}';

No caso no teste que fiz aqui parece nao ser desta forma ne?

**Comment by lpex-code** [comment]
> Valeu pela ajuda @kevinhf35.
> 
> Gero o token desta forma:
> 
> $base64 = base64_encode("{$clientId}:{$clientSecret}");
> 
> $token = 'Basic {$base64}';
> 
> No caso no teste que fiz aqui parece nao ser desta forma ne?

Experimentei também com o token privado e token público gerado nas credenciais. Nenhuma das 3 formas deu certo.

**Comment by lpex-code** [comment]
Valeu mas consegui resolver pelo consumo direto da API 2.0
