### ISSUE TITLE
Inserir no README.md guia de instalação

### ISSUE THREAD

**Issue by albertomoreiraluiz** [tamojuno/integration-api-php-sdk#4]
Olá a todos, gostaria de saber como faço a instalação do SDK em meu projeto, se possível poderiam incluir no README o guia de instalação do SDK se ele estiver em algum repositório.

**Comment by marcosandrade22** [comment]
Consegui instalar pelo composer com o seguinte comando:
composer require tamojuno/integration-api-php-sdk:dev-main

Realmente a documentação para instalação esta faltando, localizei a versão no packagist:
https://packagist.org/packages/tamojuno/integration-api-php-sdk

**Comment by albertomoreiraluiz** [comment]
Só precisa adicionar no README.md :smile:
